- hosts: localhost
  connection: local
  tasks:
  - local_action:
      module: ec2_elb_lb
      name: "rollcage-ElasticLo-EX3JVJP8O03A"
      state: present
      region: us-east-1
      zones:
        - us-east-1b
        - us-east-1c
        - us-east-1d
      listeners:
        - protocol: http # options are http, https, ssl, tcp
          load_balancer_port: 80
          instance_port: 8888
  - local_action:
      module: ec2_asg
      name: "rollcage-WebServerGroup-DTP1RQO7C6P4"
      state: present
      region: us-east-1
