---
# tasks file for asg
- name: create launch config
  local_action:
    module: ec2_lc
    name: "{{ lc_name }}"
    image_id: "{{ image_id }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    security_groups: "{{ lc_security_groups }}"
    instance_type: "{{ instance_type }}"
    assign_public_ip: yes
  tags: launch_config

- name: create autoscale groups
  local_action:
    module: ec2_asg
    name: "{{ group_name }}"
    health_check_period: 60
    load_balancers: "{{ load_balancers }}"
    health_check_type: ELB
    availability_zones: "{{ availability_zones | join(',')}}"
    launch_config_name: "{{ lc_name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ region }}"
    vpc_zone_identifier: "{{ asg_subnets | join(',') }}"
  tags: autoscale_group