- hosts: localhost
  connection: local
  gather_facts: no

  tasks:


  - name: collect instance info
    local_action: ec2_asg_facts name=rollingAMI region=us-east-1
    register: result

  - name: name instances
    set_fact: 
      old_instances: "{{ result.instances | map(attribute='instance_id') | list  }}"


  - name: loop through results
    ec2_asg_instance_swap: 
      name: rollingAMI 
      instance_ids: "{{ item }}" 
      region: us-east-1
    with_items: 
    - "{{ old_instances | batch(2) | list }}"

