# temporarily increase the desired_capacity and minimum_size by
# the batch_size
- name: set temporary settings
  ec2_asg:
    name: "{{ asg_group_name }}"
    health_check_period: 60
    health_check_type: ELB
    launch_config_name: "{{ lc_name }}"
    min_size: "{{ tmp_min_size }}"
    max_size: "{{ tmp_max_size }}"
    desired_capacity: "{{ tmp_desired_capacity }}"
    region: "{{ region }}"
  register: result
  until: result.viable_instances|int >= tmp_desired_capacity|int
  delay: 10
  retries: 120
  tags: autoscale_group

- name: loop through old instances and terminate them
  ec2_asg: 
    name: "{{ asg_group_name }}"
    replace_instances: "{{ item }}"
    region: "{{ region }}"
  with_items: 
  - "{{ asg_result.instances | batch(batch_size) | list }}"

- name: return ASG settings to normal
  ec2_asg:
    name: "{{ asg_group_name }}"
    health_check_period: 60
    health_check_type: ELB
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ region }}"