  # temporarily increase the desired_capacity and minimum_size by
  # the batch_size
- name: set temporary settings
  ec2_asg: name={{ asg_group_name }}
           region={{ region }}
           desired_capacity={{ tmp_desired_capacity }}
           min_size={{ tmp_min_size }}

- name: wait for number_of_healthy_instances >= desired_capacity
  ec2_asg: name={{ asg_group_name }} region={{ region }}
  register: result
  until: result.healthy_instances >= tmp_min_size|int and result.in_service_instances >= tmp_min_size|int
  delay: 10
  retries: 120

- name: loop through instances and terminate them
  ec2_asg: 
    name: rollingAMI 
    instance_ids: "{{ item }}" 
    region: us-east-1
  with_items: 
  - "{{ result.instances | batch(batch_size) | list }}"

- name: return ASG settings to normal
  ec2_asg: name={{ asg_group_name }} region={{ region }}
           desired_capacity={{ asg_desired_capacity }}
           min_size={{ asg_min_size }}