---
# defaults file for myapp_infra
region: us-east-1
app_name: myapp
subnets:
  - cidr: 172.22.1.0/24
    resource_tags: { "Name":"{{ app_name }}-1" }
    az: us-east-1b
  - cidr: 172.22.2.0/24
    resource_tags: { "Name":"{{ app_name }}-2" }
    az: us-east-1c 
route_tables:
  - subnets:
      - 172.22.1.0/24
      - 172.22.2.0/24
    routes:
      - dest: 0.0.0.0/0
        gw: igw